export const images = {
  LOGO: require('../../assets/images/logo.png'),
  icOpenEye: require('../../assets/images/icOpenEye.png'),
  icCloseEye: require('../../assets/images/icCloseEye.png'),
  icBack: require('../../assets/images/icBack.png'),
  icMenu: require('../../assets/images/icMenu.png'),
  google: require('../../assets/images/google.png'),
  faceboook: require('../../assets/images/facebook.png'),
  obCameraImage: require('../../assets/images/obcamera.png'),
  filldot: require('../../assets/images/filldot.png'),
  blankdot: require('../../assets/images/blankdot.png'),
  home: require('../../assets/images/home.png'),
  feed: require('../../assets/images/feed.png'),
  chart: require('../../assets/images/chart.png'),
  user: require('../../assets/images/user.png'),
  feedWhite: require('../../assets/images/feedWhite.png'),
  homeWhite: require('../../assets/images/homeWhitee.png'),
  chartWhite: require('../../assets/images/chartWhite.png'),
  userWhite: require('../../assets/images/userWhite.png'),
  dropDownArrow: require('../../assets/images/droparrow.png'),
  userProfile: require('../../assets/images/profilepic.png'),
  threeDots: require('../../assets/images/moredots.png'),
  comment: require('../../assets/images/comment.png'),
  multicolor: require('../../assets/images/ratingcolor.png'),
  picker: require('../../assets/images/triangle.png'),
  toggle: require('../../assets/images/toggle.png'),
  smallLogo: require('../../assets/images/smalllogo.png'),
  greenDoctor: require('../../assets/images/greenDoctor.png'),
  whiteDoctor: require('../../assets/images/whiteDoctor.png'),
  greenUser: require('../../assets/images/greenUser.png'),
  whiteUser: require('../../assets/images/whiteUser.png'),
  selected: require('../../assets/images/selected.png'),
  dropDown: require('../../assets/images/droparrow.png'),
  demoImage: require('../../assets/images/demoimage.png'),
  rightImg: require('../../assets/images/rightimg.png'),
  leftImg: require('../../assets/images/leftimg.png'),
  calendar: require('../../assets/images/calendar.png'),
  icCalendar: require('../../assets/images/icCalendar.png'),
  drawer: require('../../assets/images/drawer.png'),
  closeDrawer: require('../../assets/images/Cross.png'),
  selectedTitle: require('../../assets/images/selectedTitle.png'),
  notification: require('../../assets/images/notification.png'),
  arrow: require('../../assets/images/arrow.png'),
  circle: require('../../assets/images/sliderCircle.png'),
  backgroundImage: require('../../assets/images/bgImage.png'),
  deleteImg: require('../../assets/images/delete.png'),
  editImg: require('../../assets/images/edit.png'),
  edit: require('../../assets/images/icedit.png'),
  fb: require('../../assets/images/fb.png'),
  twitter: require('../../assets/images/twitter.png'),
  icon: require('../../assets/images/icon.png'),
  noDatafound: require('../../assets/images/noDatafound.png'),
  add: require('../../assets/images/add.png'),
  cardbg: require('../../assets/images/cardBg.png'),
  icleft: require('../../assets/images/icleft.png'),
  icright: require('../../assets/images/icright.png'),
  send: require('../../assets/images/sendInput.png'),
  icStripe: require('../../assets/images/Stripe.png'),
  icPayPal: require('../../assets/images/PayPal.png'),
  icTick: require('../../assets/images/icTick.png'),
  arrowDownIcon: require('../../assets/images/arrowDownIcon.png'),
  arrowUpIcon: require('../../assets/images/arrowUpIcon.png'),
  icTrash: require('../../assets/images/trash.png'),
};

export const constants = {
  baseUrl: 'https://diagnozi.com/staging/api/',
  WebAbout: 'https://diagnozi.com/staging/page/about-us',
  WebContact: 'https://diagnozi.com/staging/contact',
  WebServices: 'https://diagnozi.com/staging/page/services',

  asyncFcmToken: 'FCMToken',

  apiSuccess: true,
  apiFailure: 'failure',
  error1: 'Not found any Diseases',
  error2: 'You have not any comments',

  signup: 'signup',
  password: 'password',
  calendar: 'calendar',
  facebook: 'facebook',
  google: 'google',

  formData: 'formdata',
  withdrawRequest: 'Withdraw Request',
  enterReason: 'Enter your reason',

  //async data key
  userData: 'userData',
  isUploadStart: 'isUploadStart',

  //end points of Url
  endPtCountries: 'countries',
  endPtCategory: 'category',
  endPtRegister: 'register',
  endPtLogin: 'login',
  endPtFeed: 'feed',
  endPtFeedDetail: 'order/detail',
  endPtFeedOrderComment: 'order/comment',
  endPtFeedQuestions: 'questions',
  endPtAddComment: 'comment/add',
  endPtUpdateComment: 'comment/update',
  endPtDeleteComment: 'comment/delete',
  endPtDeleteOrder: 'order/delete',
  endPtSocialLogin: 'social-login',
  endPtUserTypeUpdate: 'user/type/update',
  endPtDoctorDocumentVerification: 'doctor/documents/save',
  endPtDoctorDocumentVerificationStatus: 'doctor/profile/status',
  endPtChangePassword: 'user/change-password',
  endPtCreateOrder: 'user/create-order',
  endPtUpdateOrder: 'user/update-order',
  endPtMyValue: 'my-order',
  endPtDiscover: 'discover',
  // endPtVote: 'order-vote',
  endPtRating: 'doctor/rating/list',
  endPtNotification: 'notification',
  endPtReferral: 'user/referal',
  endPtUserCredit: 'user/credit',
  endPtUserProfile: 'user/profile',
  endPtVote: 'doctor/order-vote',
  endPtStripeDeposit: 'stripe-payment-deposit',
  endPtStripeBuy: 'stripe-payment-buy',
  endPtPayPalBuy: 'paypal-payment-buy',
  endPtPayPalDeposit: 'paypal-payment-deposit',
  endPtCallBackPayPal: 'paypal-payment-callback',
  endPtSubscriptionHistory: 'user/subscription/history',
  endPtSubscriptionWithoutPackage: 'user/subscription/active',
  endPtMembership: 'membership',
  endPtUpdateProfile: 'user/profile/update',
  endPtTransaction: 'user/transactions',
  endPtWithdrawHistory: 'user/withdraw-request',
  endPtWithdrawRequest: 'user/send-withdraw-request',
  endPtFcm: 'user/devicetoken/update',
  endPtReadNotification: 'notification/update/readstatus',
  endPtDeleteNotification: 'notification/delete',
  endPtNotificationCount: 'notification/unread/count',

  //home header tabs
  tab1: 'tab1',
  tab2: 'tabs2',

  // payment methods
  stripe: 'Stripe',
  paypal: 'PayPal',

  push_topic_user: 'diagnozi_user',
  push_topic_doctor: 'diagnozi_doctor',
  push_navigation_feed: 'feed_detail',
};

export const regex = {
  email: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  password:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\\\[\\\](){}?\\\\|,.<>;/'":`.!~*_@#$%^&+=\-])(?=.{8,})/,
  phoneNumber:
    /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/,
  notNumber: /^([^0-9]*)$/,
  notSpace: /^\S*$/,
};

export const apiKeys = {
  google: {
    webClientId:
      '917833665058-up5lvgqds0hr7v0bg31q1i9k5atovksc.apps.googleusercontent.com',
    iosClientId:
      '917833665058-k2ovi6bs5bvrmdfn337uonlgs6jruhk7.apps.googleusercontent.com',
  },
  stripe: {
    publishableKey: 'pk_test_rCHjMEuqVUFiQuk1F9qk1WkH',
  },
};
